version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    image: postgres:13.5
    restart: always
    user: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres: {}

networks:
  postgres:
    driver: bridge
